alter table public.contact_messages
add column if not exists deleted_at timestamptz;

create index if not exists contact_messages_deleted_at_idx
on public.contact_messages (deleted_at);

create table if not exists public.deleted_contact_messages (
  id bigint generated by default as identity primary key,
  original_message_id bigint,
  name text,
  email text,
  role text,
  subject text,
  message text,
  is_read boolean default false,
  is_archived boolean default false,
  is_starred boolean default false,
  original_created_at timestamptz,
  deleted_at timestamptz not null default timezone('utc', now()),
  deleted_by text
);

create index if not exists deleted_contact_messages_original_message_id_idx
on public.deleted_contact_messages (original_message_id);

create index if not exists deleted_contact_messages_deleted_at_idx
on public.deleted_contact_messages (deleted_at);
